[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && php artisan optimize"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"