# For railway.toml
[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && php artisan optimize"

# If you're using Dockerfile, update the RUN command:
RUN npm install && NODE_OPTIONS='--experimental-json-modules' npm run build && php artisan optimize